### ISSUE TITLE
기존의 테스트 코드 오류들 발생

### ISSUE THREAD

**Issue by ytw9699** [ytw9699/Dokky#338]
- 전반적으로 테스트 코드 작성을 계속해서 미뤄오는 바람에..관리가 되지 않고 있다.
- 기존의 테스트 코드도 성공했던 것들이 모두 실패로 뜸

모든 테스트 코드 메소드에서 동일 오류발생
https://github.com/ytw9699/Dokky/blob/master/dokky/src/test/java/org/my/controller/BoardControllerTests.java

## 주요 오류 키워드
commonWebsocketHandler쪽에서 무슨 문제가 있어보인다. 빈생성이 안된다는건데..
- BeanInstantiationException
- BeanCreationException
- 아니면 WebSocketHandlerMapping , urlMap 과 같은 키워드를 보면 맵핑에서 문제가있는지..?
- No suitable default RequestUpgradeStrategy found

## 반복되는 오류 상세 내용
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.socket.server.support.WebSocketHandlerMapping#0': Cannot resolve reference to bean 'org.springframework.web.socket.server.support.WebSocketHttpRequestHandler#0' while setting bean property 'urlMap' with key [/commonWebsocketHandler]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.socket.server.support.WebSocketHttpRequestHandler#0': Cannot resolve reference to bean 'org.springframework.web.socket.server.support.DefaultHandshakeHandler#0' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.socket.server.support.DefaultHandshakeHandler#0': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.socket.server.support.DefaultHandshakeHandler]: Constructor threw exception; nested exception is java.lang.IllegalStateException: No suitable default RequestUpgradeStrategy found

**Comment by ytw9699** [comment]
모든곳에서 발생하는것처럼 보였던 이유가 아래 로직이 대부분 테스트 코드에 들어가 있었기 때문

오류가 발생하는 지점 파악

https://github.com/ytw9699/Dokky/blob/fb835370c41456003a1d4f72ccef599fe4a75b75/dokky/src/test/java/org/my/controller/BoardControllerTests.java#L49-L52

웹소켓 핸들러 객체의 의존성 주입이 뭔가 안되는것 같다..

**Comment by ytw9699** [comment]
아래 부분을 삭제하면 테스트가 성공한다.
https://github.com/ytw9699/Dokky/blob/d1d07c39c75a792eb5cdf1ddc63c4ef0de400294/dokky/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml#L69-L77

그러니까 이부분에서 http세션과의 연관성이 있어서 인거 같은데..

로그인이 안된상태이기 때문으로 생각이 든다. 결국 로그인처리부터 해결해 봐야 할거 같다.

**Comment by ytw9699** [comment]
다시 생각해보니 아닌거 같다. 


private MockMvc mockMvc; 
							
	@Before
	public void setup() {
		this.mockMvc = MockMvcBuilders.webAppContextSetup(ctx).build();
	}

가짜 mvc를 만드는데 로그인이 필요한것도 아니고

아래 부분이 로그인을 안해서 문제가 있는거라면
톰캣 실행을 하면 똑같이 문제가 생겨야 한다. 로그인을 안한 상태로도 잘 돌아가기 때문
https://github.com/ytw9699/Dokky/blob/d1d07c39c75a792eb5cdf1ddc63c4ef0de400294/dokky/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml#L69-L77





스프링이 돌면서 객체 관계를 구성할때

**Comment by ytw9699** [comment]
ERROR: org.springframework.test.context.TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@5f282abb] to prepare test instance [org.my.persistence.sqlsessionTests@4339baec]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.resource.ResourceHttpRequestHandler#0': Invocation of init method failed; nested exception is java.lang.IllegalStateException: WebApplicationObjectSupport instance [ResourceHttpRequestHandler [locations=[class path resource [resources/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@de8039f]]] does not run in a WebApplicationContext but in: org.springframework.context.support.GenericApplicationContext@7b69c6ba: startup date [Sat Jan 23 22:28:41 KST 2021]; root of context hierarchy
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:107)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 25 more
Caused by: java.lang.IllegalStateException: WebApplicationObjectSupport instance [ResourceHttpRequestHandler [locations=[class path resource [resources/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@de8039f]]] does not run in a WebApplicationContext but in: org.springframework.context.support.GenericApplicationContext@7b69c6ba: startup date [Sat Jan 23 22:28:41 KST 2021]; root of context hierarchy
	at org.springframework.web.context.support.WebApplicationObjectSupport.getWebApplicationContext(WebApplicationObjectSupport.java:114)
	at org.springframework.web.context.support.WebApplicationObjectSupport.getServletContext(WebApplicationObjectSupport.java:133)
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.initContentNegotiationStrategy(ResourceHttpRequestHandler.java:416)
	at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.afterPropertiesSet(ResourceHttpRequestHandler.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1753)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1690)
	... 40 more

**Comment by ytw9699** [comment]
웹소켓을 추가한후부터 이런 일이 결과가 나온거봐서는 웹소켓 추가로 인한 설정이 필요한것같다.
테스트에 대해 잘모르는데 분명 테스트에서도 설정이 필요할것같다.

**Comment by ytw9699** [comment]
https://stackoverflow.com/questions/21565598/no-suitable-default-requestupgradestrategy-found

**Comment by ytw9699** [comment]
`
<dependency>
`
		`<groupId>org.apache.tomcat.embed</groupId>`
		`<artifactId>tomcat-embed-websocket</artifactId>`
		`<version>9.0.16</version>`
`
</dependency>
`

테스트를 위해서는 tomcat-embed-websocket 이 필요한것같다.
dependency해주니 해결됬다.
